name: Build & Test
on: [push]
jobs:
  build-and-test:
    runs-on:
      - macos-latest
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: bazel build //...
      - run: bazel run //test:awscli_run
