name: Build & Test
on: [push]
jobs:
  build-and-test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: bazel build //...
      - run: bazel run //test:awscli_run
